### ISSUE TITLE
Research the best way and add colors to templates

### ISSUE THREAD

**Issue by akalipetis** [platformsh/platformify#37]
Depends on #35

We must research how to add colors in multiple terminal profiles that match the design as closely as possible. If this presents to be an issue, we'll need to define a set of colors that work nicely across profiles and then ask the design team what's the best way to use them.

A potential list of "safe" colors might be:

* Cyan
* Blue
* Yellow
* Red

## Tasks

- [ ] Research how to add colors to different terminal profiles
- [ ] Create a list of "safe" colors to use in multiple terminal profiles
- [ ] Use the colors decided by the design team

## Resources

* Design - https://www.figma.com/file/NFEdIEtxvmfQ0NiliDHZ62/CLI-onboarding-process?node-id=308-71&t=Tq42wsmoDhrDEFP2-0
