### ISSUE TITLE
Rework the service selection question flow

### ISSUE THREAD

**Issue by akalipetis** [platformsh/platformify#39]
We need to rework the service selection question flow. The goal is to reduce questions and make it easier for the user.

### Tasks

- [ ] Automatically infer the service name from the service type instead of asking(`redis` for Redis, etc)
- [ ] Default to 1024 storage for storage-backed services instead of asking
- [ ] Switch from multiple selects to one multi-select to simplify the question - no need to handle multiple services of the same type for now
