### ISSUE TITLE
Create a flow to Platformify a Laravel PHP project

### ISSUE THREAD

**Issue by akalipetis** [platformsh/platformify#5]
This flow should include the following steps as part of Platformifying the project:

- [x] Select the PHP version
- [x] Select the database type
- [ ] Select the cache type, if any
- [ ] Install the needed dependencies in composer
- [ ] Create the `.platform.app.yaml` file
- [ ] Create the `.platform/services.yaml` file

## Tasks

- [x] #18
- [x] #19
- [x] #20

## Resources

* https://docs.platform.sh/guides/laravel.html
* https://docs.platform.sh/guides/laravel/deploy/bridge.html

[^1]: https://github.com/platformsh/platformify/pull/17
