### ISSUE TITLE
Skip the listening interface question and use whatever is already used in the templates

### ISSUE THREAD

**Issue by lolautruche** [platformsh/platformify#54]
We need to skip the listening interface question and use whatever is already used in the templates.

```[tasklist]
### Tasks
- [ ] Laravel: Skip the web key altogether - related to #56 
- [ ] Django: unix
- [ ] Next.js: tcp
- [ ] Rest PHP: same as Laravel
- [ ] Rest non-PHP: unix
```

---

## Original description

From a user standpoint, it's hard to figure out what to choose. The user might not understand why we're asking this, and it's not really important.
What about using a default here? UNIX?
