### ISSUE TITLE
Web start command is irrelevant for PHP

### ISSUE THREAD

**Issue by lolautruche** [platformsh/platformify#56]
We should remove the web start command from PHP projects completely and automate it for the rest of the stacks.

```[tasklist]
### Tasks
- [ ] All PHP: remove the question and fallback to a commented area in the file, pointing to https://docs.platform.sh/languages/php.html#alternate-start-commands
- [ ] Django: use the current default, without asking the question
- [ ] Next.js: use the current default, without asking the question
- [ ] Generic: see below
```

#### Generic

Add the following command

```console
echo "Put your web server command in here! You need to listen to '$SOCKET' unix socket. Read more about it here: https://docs.platform.sh/create-apps/app-reference.html#web-commands
```

---

## Original description

Except in very specific cases, PHP doesn't need a web start command.
The problem with it is that when using the Laravel stack, the web start command is empty in the generated file, making it invalid.

At the very least, if not removing the question entirely (see #55 ), it should be removed from the Laravel stack
