### ISSUE TITLE
Detect the stack beforehand

### ISSUE THREAD

**Issue by lolautruche** [platformsh/platformify#60]
We should skip the stack question, in case we can automatically detect the stack. Auto-detection should happen as follows:

```[tasklist]
### Tasks
- [x] Django: check if the `manage.py` file exists
- [ ] Next.js: check that a `package.json` file exists and contains the following packages: next react react-dom
- [ ] Laravel: check that `composer.json` file exists and contains `laravel`
```

If no stack is detected, we should choose generic and ask the runtime question next. If there's a better way to detect Next.js or Laravel, by all means do that instead.

---

## Original description

It should be possible to at least preselect the current stack
