### ISSUE TITLE
Validate generated YAML files

### ISSUE THREAD

**Issue by akalipetis** [platformsh/platformify#79]
We need to add tests, validating the generated YAML files for all Platformifiers. The validation should make sure that the YAML files are both valid YAML and they follow the Platform.sh configuration files schema.

```[tasklist]
### Tasks
- [x] Create integration tests that run Platformify and generate YAML files using all Platformifiers
- [x] Validate the the generated YAML files are valid YAML
- [ ] https://github.com/platformsh/platformify/issues/101
```

If the bonus task proves to expand the scope of this task a lot, we can open it as a separate ticket.

#### Platformifier tests

In here, we should try a few different scenarios (2-3 should be enough for starters), which should tests a happy scenario and 1-2 corner cases for each Platformifier. For each scenario, we should have the expected YAML and then test they're equal using `reflect.DeepEqual`[^1]. The loading should be done using plain `map[string]interface{}` variables, to make sure there are no missing fields.

[^1]: https://pkg.go.dev/reflect#DeepEqual
