### ISSUE TITLE
Add support for the registry.json for the generic stack

### ISSUE THREAD

**Issue by akalipetis** [platformsh/platformify#80]
We should use the `registry.json` provided in our docs[^1] instead of the hardcoded values we currently have in order to list the available runtimes, services and their latest values. The `registry.json` should have a default file in each build used as fallback, but the list should be refreshed daily from the docs endpoint.

```[tasklist]
### Tasks
- [ ] Store the registry.json file in the repository and use it to generate the lists and defaults for runtimes and services
- [ ] Add support for loading the latest registry.json from the docs URL
- [ ] Cache the latest registry.json and do not download it again for the next 24h
```

### Technical implementation

* Use the same mechanism for storing the latest `registry.json` file inside the binary, using embed[^2]
* Use a caching directory for storing the file  - default to `~/.platformsh/cache/` - the current Legacy CLI cache implementation is the one provided by doctrine using `FilesystemCache`[^3]

[^1]: https://docs.platform.sh/registry/images/registry.json
[^2]: https://pkg.go.dev/embed
[^3]: https://www.doctrine-project.org/projects/doctrine-cache/en/1.10/index.html#filesystemcache
