### ISSUE TITLE
Create a new validate command that validates currently available YAML files

### ISSUE THREAD

**Issue by akalipetis** [platformsh/platformify#81]
We need to create a `platformify validate` command, that will be available as `platform app:config-validate` and `platform validate` command in the CLI.

The command should validate the following things:

* The current directory is a Git repository
* There is at least one `.platform.app.yaml` file or a `.platform/applications.yaml` file
* All the Platform.sh configuration files are valid (`.platform/routes.yaml`, `.platform/services.yaml`, `.platform.app.yaml` and `.platform/applications.yaml`)

```[tasklist]
### Tasks

- [ ] Create the `platformify validate` command
- [ ] Expose the `platform app:config-validate` and `platform validate` commands to the CLI
- [ ] Include the `platform app:config-validate` command in the `platform list` and `platform list app` commands like we've done for `platform project:init`
```

The `platform app:config-validate` was chosen to follow `platform app:config-get`.
